import { createFactories } from './batch-helpers.mjs';

export function buildBatch4(slotMeta) {
  const { mcq, tf, short, si } = createFactories(slotMeta, 'matrix-bank-v4-variant');
  return [
    // P1_01
    mcq('P1_01', 8,
      { vi: 'Giá trị của $\\sin 60^\\circ$ là', en: 'The value of $\\sin 60^\\circ$ is' },
      ['$\\dfrac{\\sqrt{3}}{2}$', '$\\dfrac{1}{2}$', '$\\dfrac{\\sqrt{2}}{2}$', '$1$'], 'A',
      { vi: '$\\sin 60^\\circ = \\dfrac{\\sqrt{3}}{2}$.', en: '$\\sin 60^\\circ = \\dfrac{\\sqrt{3}}{2}$.' },
      { vi: '**Góc đặc biệt:** $\\sin 60^\\circ = \\dfrac{\\sqrt{3}}{2}$. **Kết luận.** Chọn **A**.', en: '**Special angle.** $\\sin 60^\\circ = \\dfrac{\\sqrt{3}}{2}$. Choose **A**.' },
      { vi: 'Hay nhầm với $\\sin 30^\\circ$ hoặc $\\sin 45^\\circ$.', en: 'Do not confuse with $\\sin 30^\\circ$ or $\\sin 45^\\circ$.' }),
    mcq('P1_01', 9,
      { vi: 'Giá trị của $\\cos 45^\\circ$ là', en: 'The value of $\\cos 45^\\circ$ is' },
      ['$\\dfrac{\\sqrt{2}}{2}$', '$\\dfrac{1}{2}$', '$\\dfrac{\\sqrt{3}}{2}$', '$0$'], 'A',
      { vi: '$\\cos 45^\\circ = \\dfrac{\\sqrt{2}}{2}$.', en: '$\\cos 45^\\circ = \\dfrac{\\sqrt{2}}{2}$.' },
      { vi: '**Góc đặc biệt:** tam giác vuông cân nên $\\cos 45^\\circ = \\dfrac{\\sqrt{2}}{2}$. **Kết luận.** Chọn **A**.', en: '**Special angle.** $\\cos 45^\\circ = \\dfrac{\\sqrt{2}}{2}$. Choose **A**.' },
      { vi: 'Hay nhầm với $\\cos 60^\\circ$ hoặc $\\cos 30^\\circ$.', en: 'Do not confuse with $\\cos 60^\\circ$ or $\\cos 30^\\circ$.' }),

    // P1_02
    mcq('P1_02', 8,
      { vi: 'Cho cấp số cộng $(u_n)$ có $u_1 = 3$, $d = 2$. Giá trị $u_5$ bằng', en: 'An AP has $u_1 = 3$, $d = 2$. Find $u_5$.' },
      ['$11$', '$9$', '$13$', '$7$'], 'A',
      { vi: '$u_5 = 3 + 4 \\cdot 2 = 11$.', en: '$u_5 = 3 + 4 \\cdot 2 = 11$.' },
      { vi: '**Công thức:** $u_5 = u_1 + 4d = 3 + 8 = 11$. **Kết luận.** Chọn **A**.', en: '**Formula:** $u_5 = u_1 + 4d = 11$.' },
      { vi: 'Số hạng thứ $5$ cách $u_1$ đúng $4$ công sai.', en: 'The fifth term is $u_1 + 4d$, not $u_1 + 5d$.' }),
    mcq('P1_02', 9,
      { vi: 'Cho cấp số nhân $(u_n)$ có $u_1 = 2$, $q = 3$. Giá trị $u_5$ bằng', en: 'A GP has $u_1 = 2$, $q = 3$. Find $u_5$.' },
      ['$162$', '$54$', '$486$', '$81$'], 'A',
      { vi: '$u_5 = 2 \\cdot 3^4 = 162$.', en: '$u_5 = 2 \\cdot 3^4 = 162$.' },
      { vi: '**Công thức:** $u_5 = u_1 q^4 = 2 \\cdot 81 = 162$. **Kết luận.** Chọn **A**.', en: '**Formula:** $u_5 = u_1 q^4 = 162$.' },
      { vi: 'Số mũ là $n-1=4$, không phải $5$.', en: 'Exponent is $n-1=4$, not $5$.' }),

    // P1_03
    mcq('P1_03', 8,
      { vi: 'Lăng trụ đứng có đáy vuông cạnh $5$, chiều cao $4$. Thể tích bằng', en: 'A right prism has square base side $5$ and height $4$. Its volume is' },
      ['$100$', '$80$', '$125$', '$20$'], 'A',
      { vi: '$V = 5^2 \\cdot 4 = 100$.', en: '$V = 25 \\cdot 4 = 100$.' },
      { vi: '**Công thức:** $V = S_{\\text{đáy}} \\cdot h = 25 \\cdot 4 = 100$. **Kết luận.** Chọn **A**.', en: '**Formula:** $V = 25 \\cdot 4 = 100$.' },
      { vi: 'Đáy vuông cạnh $5$ → diện tích $25$, không phải $5$.', en: 'Square side $5$ gives base area $25$.' }),
    mcq('P1_03', 9,
      { vi: 'Chóp $S.ABC$ có đáy tam giác vuông tại $A$, $AB=3$, $AC=4$, $SA=5$ vuông góc mặt phẳng đáy. Thể tích bằng', en: 'Pyramid $S.ABC$ has right triangle base $AB=3$, $AC=4$, and $SA=5$ perpendicular to the base. Volume is' },
      ['$10$', '$30$', '$60$', '$20$'], 'A',
      { vi: '$V = \\dfrac{1}{3} \\cdot \\dfrac{1}{2} \\cdot 3 \\cdot 4 \\cdot 5 = 10$.', en: '$V = \\dfrac{1}{3} \\cdot 6 \\cdot 5 = 10$.' },
      { vi: '**Bước 1.** $S_{\\text{đáy}} = \\dfrac{1}{2} \\cdot 3 \\cdot 4 = 6$. **Bước 2.** $V = \\dfrac{1}{3} \\cdot 6 \\cdot 5 = 10$. **Kết luận.** Chọn **A**.', en: '**Steps.** Base area $6$, $V = 10$.' },
      { vi: 'Thể tích chóp có hệ số $\\dfrac{1}{3}$; chiều cao là $SA=5$.', en: 'Pyramid factor $\\dfrac{1}{3}$; height is $SA$.' }),

    // P1_04
    mcq('P1_04', 8,
      { vi: 'Một hình cầu có bán kính $R = 5$. Thể tích bằng', en: 'A sphere has radius $R = 5$. Its volume is' },
      ['$\\dfrac{500\\pi}{3}$', '$125\\pi$', '$\\dfrac{250\\pi}{3}$', '$500\\pi$'], 'A',
      { vi: '$V = \\dfrac{4}{3}\\pi R^3 = \\dfrac{500\\pi}{3}$.', en: '$V = \\dfrac{4}{3}\\pi \\cdot 125 = \\dfrac{500\\pi}{3}$.' },
      { vi: '**Công thức:** $V = \\dfrac{4}{3}\\pi \\cdot 125 = \\dfrac{500\\pi}{3}$. **Kết luận.** Chọn **A**.', en: '**Formula:** $V = \\dfrac{500\\pi}{3}$.' },
      { vi: 'Nhớ lũy thừa $R^3=125$, không phải $R^2$.', en: 'Use $R^3=125$, not $R^2$.' }),
    mcq('P1_04', 9,
      { vi: 'Một hình cầu có bán kính $R = 1$. Diện tích mặt cầu bằng', en: 'A sphere has radius $R = 1$. Its surface area is' },
      ['$4\\pi$', '$\\dfrac{4\\pi}{3}$', '$2\\pi$', '$\\pi$'], 'A',
      { vi: '$S = 4\\pi R^2 = 4\\pi$.', en: '$S = 4\\pi \\cdot 1 = 4\\pi$.' },
      { vi: '**Công thức:** $S = 4\\pi R^2 = 4\\pi$. **Kết luận.** Chọn **A**.', en: '**Formula:** $S = 4\\pi$.' },
      { vi: 'Diện tích mặt cầu dùng $4\\pi R^2$, không phải thể tích.', en: 'Surface area uses $4\\pi R^2$, not volume formula.' }),

    // P1_05
    mcq('P1_05', 8,
      { vi: 'Nghiệm của phương trình $2^x = 32$ là', en: 'The solution of $2^x = 32$ is' },
      ['$5$', '$4$', '$6$', '$16$'], 'A',
      { vi: '$2^x = 2^5 \\Leftrightarrow x = 5$.', en: '$2^x = 2^5 \\Leftrightarrow x = 5$.' },
      { vi: '**Bước 1.** $32 = 2^5$. **Bước 2.** $x = 5$. **Kết luận.** Chọn **A**.', en: '**Step 1.** $32 = 2^5$. **Answer:** $x = 5$.' },
      { vi: 'Đồng cơ số: $2^x = 2^5 \\Rightarrow x = 5$.', en: 'Same base: $x = 5$.' }),
    mcq('P1_05', 9,
      { vi: 'Nghiệm của phương trình $\\log_2 x = 4$ là', en: 'The solution of $\\log_2 x = 4$ is' },
      ['$16$', '$8$', '$4$', '$2$'], 'A',
      { vi: '$x = 2^4 = 16$.', en: '$x = 2^4 = 16$.' },
      { vi: '**Định nghĩa:** $\\log_2 x = 4 \\Leftrightarrow x = 2^4 = 16$. **Kết luận.** Chọn **A**.', en: '**Definition:** $x = 16$.' },
      { vi: 'Đừng nhầm $x = 4$ hoặc $x = 2$.', en: 'Do not answer $x = 4$ or $x = 2$.' }),

    // P1_06
    mcq('P1_06', 8,
      { vi: 'Trung bình cộng của $2$, $4$, $6$, $8$ bằng', en: 'The mean of $2$, $4$, $6$, $8$ is' },
      ['$5$', '$4$', '$6$', '$20$'], 'A',
      { vi: '$\\dfrac{2+4+6+8}{4} = 5$.', en: '$(2+4+6+8)/4 = 5$.' },
      { vi: '**Công thức:** $\\bar{x} = \\dfrac{20}{4} = 5$. **Kết luận.** Chọn **A**.', en: '**Mean:** $20/4 = 5$.' },
      { vi: 'Chia cho số lượng $4$, không phải $3$.', en: 'Divide by count $4$.' }),
    mcq('P1_06', 9,
      { vi: 'Dãy số liệu ghép nhóm: $[0;5)$ có $4$ phần tử, $[5;10)$ có $6$ phần tử, $[10;15)$ có $8$ phần tử. Trung vị thuộc khoảng', en: 'Grouped data: $[0,5)$ has $4$, $[5,10)$ has $6$, $[10,15)$ has $8$. The median lies in' },
      ['$[10;15)$', '$[5;10)$', '$[0;5)$', 'Không xác định'], 'A',
      { vi: '$n=18$, vị trí trung vị $9$–$10$ nằm trong nhóm $[10;15)$.', en: 'Median positions $9$–$10$ fall in $[10,15)$.' },
      { vi: '**Bước 1.** $n=18$, trung vị ở vị trí $9$ và $10$. **Bước 2.** Tích lũy: $4$, $10$, $18$ → thuộc $[10;15)$. **Kết luận.** Chọn **A**.', en: '**Step 1.** $n=18$. **Step 2.** Median in third group.' },
      { vi: 'Tính tích lũy tần số trước khi xác định nhóm chứa trung vị.', en: 'Use cumulative frequency first.' }),

    // P1_07
    mcq('P1_07', 8,
      { vi: 'Đạo hàm của $f(x) = x^2 + 5x$ là', en: 'The derivative of $f(x) = x^2 + 5x$ is' },
      ['$2x + 5$', '$2x$', '$x^2 + 5$', '$2x + 5x$'], 'A',
      { vi: "$f'(x) = 2x + 5$.", en: "$f'(x) = 2x + 5$." },
      { vi: "**Bước 1.** $(x^2)' = 2x$, $(5x)' = 5$. **Kết luận.** Chọn **A**.", en: "**Derivative:** $2x + 5$." },
      { vi: 'Đạo hàm của $5x$ là $5$, không phải $0$.', en: "Derivative of $5x$ is $5$, not $0$." }),
    mcq('P1_07', 9,
      { vi: 'Đạo hàm của $f(x) = x^2 - 4x + 1$ tại $x = 2$ bằng', en: "The derivative of $f(x) = x^2 - 4x + 1$ at $x = 2$ is" },
      ['$0$', '$1$', '$-4$', '$4$'], 'A',
      { vi: "$f'(x) = 2x - 4$, $f'(2) = 0$.", en: "$f'(2) = 0$." },
      { vi: "**Bước 1.** $f'(x) = 2x - 4$. **Bước 2.** $f'(2) = 0$. **Kết luận.** Chọn **A**.", en: "**Step 2.** $f'(2) = 0$." },
      { vi: 'Sau khi tìm $f\'(x)$, thế $x=2$.', en: 'Substitute $x=2$ into $f\'(x)$.' }),

    // P1_08
    mcq('P1_08', 8,
      { vi: 'Nguyên hàm của $f(x) = x^3$ là', en: 'An antiderivative of $f(x) = x^3$ is' },
      ['$\\dfrac{x^4}{4} + C$', '$3x^2 + C$', '$x^4 + C$', '$\\dfrac{x^3}{3} + C$'], 'A',
      { vi: '$\\int x^3\\,dx = \\dfrac{x^4}{4} + C$.', en: '$\\int x^3\\,dx = x^4/4 + C$.' },
      { vi: '**Bước 1.** $\\int x^3\\,dx = \\dfrac{x^{3+1}}{3+1} + C = \\dfrac{x^4}{4} + C$. **Kết luận.** Chọn **A**.', en: '**Antiderivative:** $x^4/4 + C$.' },
      { vi: 'Nhớ chia cho $(n+1)$ khi lũy thừa.', en: 'Divide by $(n+1)$ for powers.' }),
    mcq('P1_08', 9,
      { vi: '$\\displaystyle \\int_0^2 (3x+1)\\,dx$ bằng', en: '$\\displaystyle \\int_0^2 (3x+1)\\,dx$ equals' },
      ['$8$', '$6$', '$10$', '$4$'], 'A',
      { vi: '$\\left[\\dfrac{3x^2}{2}+x\\right]_0^2 = 6+2 = 8$.', en: '$[3x^2/2+x]_0^2 = 8$.' },
      { vi: '**Bước 1.** Nguyên hàm $\\dfrac{3x^2}{2}+x$. **Bước 2.** $F(2)-F(0)=8$. **Kết luận.** Chọn **A**.', en: '**Answer:** $8$.' },
      { vi: 'Thế cả cận dưới $0$.', en: 'Evaluate both bounds.' }),

    // P1_09
    mcq('P1_09', 8,
      { vi: 'Nguyên hàm của $f(x) = \\cos x$ là', en: 'An antiderivative of $f(x) = \\cos x$ is' },
      ['$\\sin x + C$', '$-\\sin x + C$', '$\\cos x + C$', '$-\\cos x + C$'], 'A',
      { vi: '$\\int \\cos x\\,dx = \\sin x + C$.', en: '$\\int \\cos x\\,dx = \\sin x + C$.' },
      { vi: '**Công thức:** $\\int \\cos x\\,dx = \\sin x + C$. **Kết luận.** Chọn **A**.', en: '**Formula:** $\\sin x + C$.' },
      { vi: 'Hay nhầm dấu: nguyên hàm của $\\cos x$ là $\\sin x$.', en: 'Antiderivative of $\\cos x$ is $\\sin x$.' }),
    mcq('P1_09', 9,
      { vi: '$\\displaystyle \\int_0^{\\pi} \\sin x\\,dx$ bằng', en: '$\\displaystyle \\int_0^{\\pi} \\sin x\\,dx$ equals' },
      ['$2$', '$0$', '$1$', '$-2$'], 'A',
      { vi: '$[-\\cos x]_0^{\\pi} = 1 - (-1) = 2$.', en: '$[-\\cos x]_0^{\\pi} = 2$.' },
      { vi: '**Bước 1.** $[-\\cos x]_0^{\\pi} = -(-1)-(-1)=2$. **Kết luận.** Chọn **A**.', en: '**Answer:** $2$.' },
      { vi: '$\\cos\\pi = -1$, không phải $1$.', en: '$\\cos\\pi = -1$.' }),

    // P1_10
    mcq('P1_10', 8,
      { vi: 'Khoảng cách từ $M(1;2;2)$ đến gốc $O$ bằng', en: 'The distance from $M(1,2,2)$ to the origin is' },
      ['$3$', '$5$', '$7$', '$9$'], 'A',
      { vi: '$OM = \\sqrt{1+4+4} = 3$.', en: '$OM = 3$.' },
      { vi: '**Công thức:** $OM = \\sqrt{1^2+2^2+2^2} = 3$. **Kết luận.** Chọn **A**.', en: '**Distance:** $3$.' },
      { vi: 'Cộng tọa độ $1+2+2=5$ là sai; phải bình phương rồi căn.', en: 'Square coordinates before the square root.' }),
    mcq('P1_10', 9,
      { vi: 'Khoảng cách từ $N(3;0;4)$ đến gốc $O$ bằng', en: 'The distance from $N(3,0,4)$ to the origin is' },
      ['$5$', '$7$', '$12$', '$25$'], 'A',
      { vi: '$ON = \\sqrt{9+0+16} = 5$.', en: '$ON = 5$.' },
      { vi: '**Bước 1.** $ON = \\sqrt{3^2+0^2+4^2} = \\sqrt{25} = 5$. **Kết luận.** Chọn **A**.', en: '**Answer:** $5$.' },
      { vi: 'Nhớ bình phương từng tọa độ trước khi cộng.', en: 'Square each coordinate first.' }),

    // P1_11
    mcq('P1_11', 8,
      { vi: 'Đường thẳng $d: \\dfrac{x-2}{3} = \\dfrac{y+1}{2} = \\dfrac{z}{1}$ có vectơ chỉ phương', en: 'Line $d: \\dfrac{x-2}{3} = \\dfrac{y+1}{2} = \\dfrac{z}{1}$ has direction vector' },
      ['$(3;2;1)$', '$(2;-1;0)$', '$(-3;-2;-1)$', '$(3;1;2)$'], 'A',
      { vi: 'Hệ số mẫu: $(3;2;1)$.', en: 'Denominators: $(3,2,1)$.' },
      { vi: '**Dạng chính tắc:** vectơ chỉ phương lấy từ mẫu $(3;2;1)$. **Kết luận.** Chọn **A**.', en: '**Direction from denominators.** Choose **A**.' },
      { vi: 'Lấy hệ số mẫu, không lấy tử hoặc đổi dấu tùy tiện.', en: 'Use denominators, not numerators.' }),
    mcq('P1_11', 9,
      { vi: 'Đường thẳng $\\dfrac{x}{2} = \\dfrac{y-1}{-1} = z+3$ có một vectơ chỉ phương là', en: 'Line $\\dfrac{x}{2} = \\dfrac{y-1}{-1} = z+3$ has direction vector' },
      ['$(2;-1;1)$', '$(2;1;-1)$', '$(1;-2;3)$', '$(-2;1;-1)$'], 'A',
      { vi: 'Viết $z+3 = \\dfrac{z+3}{1}$ nên mẫu $(2;-1;1)$.', en: 'Write $z+3$ as $(z+3)/1$; direction $(2,-1,1)$.' },
      { vi: '**Bước 1.** $z+3 = \\dfrac{z+3}{1}$. **Bước 2.** Vectơ chỉ phương $(2;-1;1)$. **Kết luận.** Chọn **A**.', en: '**Direction:** $(2,-1,1)$.' },
      { vi: 'Ẩn mẫu $1$ của $z$ vẫn là $1$, không phải $0$.', en: 'Missing denominator on $z$ means $1$.' }),

    // P1_12
    mcq('P1_12', 8,
      { vi: 'Mặt phẳng $(P): 3x - y + z - 5 = 0$ có vectơ pháp tuyến', en: 'Plane $(P): 3x - y + z - 5 = 0$ has normal vector' },
      ['$(3;-1;1)$', '$(3;1;-1)$', '$(1;-3;1)$', '$(3;-1;-1)$'], 'A',
      { vi: '$\\vec{n} = (3;-1;1)$.', en: '$\\vec{n} = (3,-1,1)$.' },
      { vi: '**Dạng $ax+by+cz+d=0$:** $\\vec{n}=(a;b;c)=(3;-1;1)$. **Kết luận.** Chọn **A**.', en: '**Coefficients:** $(3,-1,1)$.' },
      { vi: 'Hệ số $y$ là $-1$, không phải $1$.', en: '$y$-coefficient is $-1$.' }),
    mcq('P1_12', 9,
      { vi: 'Mặt phẳng $(Q): -x + 2y + z + 4 = 0$ có một vectơ pháp tuyến là', en: 'Plane $(Q): -x + 2y + z + 4 = 0$ has normal vector' },
      ['$(-1;2;1)$', '$(1;2;1)$', '$(-1;2;-1)$', '$(4;2;1)$'], 'A',
      { vi: '$\\vec{n} = (-1;2;1)$.', en: '$\\vec{n} = (-1,2,1)$.' },
      { vi: '**Đọc hệ số:** $a=-1$, $b=2$, $c=1$. **Kết luận.** Chọn **A**.', en: '**Read coefficients.** Choose **A**.' },
      { vi: 'Giữ dấu âm của $-x$; $+z$ nghĩa là hệ số $1$.', en: 'Keep the minus on $-x$; $+z$ means coefficient $1$.' }),

    // P2_01
    tf('P2_01', 8,
      { vi: 'Cho hàm số $f(x) = 2x^3 - 6x$.', en: 'Given $f(x) = 2x^3 - 6x$.' },
      [
        si('a', "$f'(x) = 6x^2 - 6$.", "$f'(x) = 6x^2 - 6$.", true, 'Đạo hàm từng hạng.', 'Term-by-term derivative.'),
        si('b', "$f'(x)=0$ có tập nghiệm $S=\\{-1;1\\}$.", "$f'(x)=0$ has solutions $\\{-1,1\\}$.", true, '$6(x^2-1)=0$.', '$6(x^2-1)=0$.'),
        si('c', 'Hàm số đồng biến trên $(-1;1)$.', 'The function is increasing on $(-1,1)$.', false, 'Giữa $-1$ và $1$, $f\'<0$ nên nghịch biến.', '$f\'<0$ between roots.'),
        si('d', 'Giá trị cực tiểu của hàm số bằng $-4$.', 'The local minimum value equals $-4$.', true, '$f(1)=2-6=-4$.', '$f(1)=-4$ at $x=1$.'),
      ],
      { vi: 'Đáp án: aĐ, bĐ, cS, dĐ.', en: 'Answers: aT, bT, cF, dT.' },
      { vi: '**Ý a–b.** $f\'=6x^2-6$, nghiệm $\\pm1$. **Ý c.** Nghịch biến trên $(-1;1)$. **Ý d.** $f(1)=-4$.', en: '**a–b.** Derivative and roots. **c.** Decreasing on $(-1,1)$. **d.** $f(1)=-4$.' },
      { vi: 'Xét dấu $f\'$ giữa hai nghiệm.', en: 'Sign-test $f\'$ between roots.' }),
    tf('P2_01', 9,
      { vi: 'Cho hàm số $f(x) = -x^2 + 6x - 5$.', en: 'Given $f(x) = -x^2 + 6x - 5$.' },
      [
        si('a', "$f'(x) = -2x + 6$.", "$f'(x) = -2x + 6$.", true, 'Đạo hàm đúng.', 'Correct derivative.'),
        si('b', "$f'(x)=0 \\Leftrightarrow x=3$.", "$f'(x)=0 \\Leftrightarrow x=3$.", true, 'Nghiệm duy nhất $x=3$.', 'Single critical point at $x=3$.'),
        si('c', 'Hàm số đạt giá trị lớn nhất tại $x=3$.', 'The function attains its maximum at $x=3$.', true, '$a=-1<0$ nên cực đại tại $x=3$.', 'Parabola opens downward.'),
        si('d', 'Giá trị lớn nhất của hàm số bằng $4$.', 'The maximum value equals $4$.', true, '$f(3)=-9+18-5=4$.', '$f(3)=4$.'),
      ],
      { vi: 'Đáp án: aĐ, bĐ, cĐ, dĐ.', en: 'Answers: aT, bT, cT, dT.' },
      { vi: '**Ý d.** $f(3)=4$.', en: '**d.** $f(3)=4$.' },
      { vi: 'Thế $x=3$ vào $f(x)$ sau khi tìm cực trị.', en: 'Substitute into $f(x)$ after finding the critical point.' }),

    // P2_02
    tf('P2_02', 8,
      { vi: 'Cho $M = \\displaystyle \\int_0^1 (x+2)\\,dx$.', en: 'Let $M = \\displaystyle \\int_0^1 (x+2)\\,dx$.' },
      [
        si('a', '$\\dfrac{x^2}{2}+2x$ là một nguyên hàm của $x+2$.', '$\\dfrac{x^2}{2}+2x$ is an antiderivative of $x+2$.', true, 'Đạo hàm ngược kiểm tra.', 'Derivative checks out.'),
        si('b', '$M = 2{,}5$.', '$M = 2.5$.', true, '$\\left[\\dfrac{x^2}{2}+2x\\right]_0^1 = 2{,}5$.', '$1/2+2=2.5$.'),
        si('c', '$M = 2$.', '$M = 2$.', false, 'Quên hạng $\\dfrac{x^2}{2}$ tại $x=1$.', 'Forgot the quadratic term.'),
        si('d', 'Hàm số dưới dấu tích phân dương trên $[0;1]$.', 'The integrand is positive on $[0,1]$.', true, '$x+2 \\ge 2>0$.', '$x+2>0$ on $[0,1]$.'),
      ],
      { vi: 'Đáp án: aĐ, bĐ, cS, dĐ.', en: 'Answers: aT, bT, cF, dT.' },
      { vi: '**Ý b.** $M=2{,}5$. **Ý c.** Bẫy chỉ lấy $2$.', en: '**b.** $M=2.5$.' },
      { vi: 'Cộng đủ hạng khi thế cận.', en: 'Include every term when evaluating bounds.' }),
    tf('P2_02', 9,
      { vi: 'Cho $N = \\displaystyle \\int_1^4 x\\,dx$.', en: 'Let $N = \\displaystyle \\int_1^4 x\\,dx$.' },
      [
        si('a', '$\\dfrac{x^2}{2}$ là một nguyên hàm của $x$.', '$\\dfrac{x^2}{2}$ is an antiderivative of $x$.', true, 'Đạo hàm đúng.', 'Correct.'),
        si('b', '$N = \\dfrac{15}{2}$.', '$N = \\dfrac{15}{2}$.', true, '$\\dfrac{16}{2}-\\dfrac{1}{2}=\\dfrac{15}{2}$.', '$8-0.5=15/2$.'),
        si('c', '$N = 8$.', '$N = 8$.', false, 'Quên trừ cận dưới.', 'Forgot lower bound.'),
        si('d', 'Giá trị trung bình của $x$ trên $[1;4]$ bằng $\\dfrac{5}{2}$.', 'The average value of $x$ on $[1,4]$ equals $\\dfrac{5}{2}$.', true, '$N/3 = (15/2)/3 = 5/2$.', 'Average $= N/3 = 5/2$.'),
      ],
      { vi: 'Đáp án: aĐ, bĐ, cS, dĐ.', en: 'Answers: aT, bT, cF, dT.' },
      { vi: '**Ý d.** Giá trị trung bình $= N/(4-1)$.', en: '**d.** Average $= N/3$.' },
      { vi: 'Tích phân xác định: $F(b)-F(a)$.', en: 'Definite integral: $F(b)-F(a)$.' }),

    // P2_03
    tf('P2_03', 8,
      { vi: 'Trong $Oxyz$, mặt phẳng $(\\gamma): x + y + z - 2 = 0$.', en: 'In $Oxyz$, plane $(\\gamma): x + y + z - 2 = 0$.' },
      [
        si('a', 'Một vectơ pháp tuyến của $(\\gamma)$ là $(1;1;1)$.', 'A normal vector is $(1,1,1)$.', true, 'Hệ số $1,1,1$.', 'Coefficients $1,1,1$.'),
        si('b', 'Gốc tọa độ $O$ thuộc $(\\gamma)$.', 'The origin lies on $(\\gamma)$.', false, '$0+0+0-2=-2\\neq0$.', '$-2\\neq0$.'),
        si('c', 'Điểm $A(2;0;0)$ thuộc $(\\gamma)$.', 'Point $A(2,0,0)$ lies on $(\\gamma)$.', true, '$2+0+0-2=0$.', '$2-2=0$.'),
        si('d', 'Khoảng cách từ $O$ đến $(\\gamma)$ bằng $2$.', 'Distance from $O$ to $(\\gamma)$ equals $2$.', false, '$d=\\dfrac{2}{\\sqrt{3}}\\neq2$.', 'Divide by $|\\vec{n}|=\\sqrt{3}$.'),
      ],
      { vi: 'Đáp án: aĐ, bS, cĐ, dS.', en: 'Answers: aT, bF, cT, dF.' },
      { vi: '**Ý b.** Thế $O$ vào phương trình. **Ý d.** $d=2/\\sqrt{3}$.', en: '**b.** Substitute $O$. **d.** $d=2/\\sqrt{3}$.' },
      { vi: 'Kiểm tra điểm thuộc mặt phẳng bằng cách thế tọa độ.', en: 'Substitute coordinates to test a point on the plane.' }),
    tf('P2_03', 9,
      { vi: 'Trong $Oxyz$, mặt phẳng $(\\delta): z = 4$ (viết dạng $0x+0y+z-4=0$).', en: 'In $Oxyz$, plane $(\\delta): z = 4$ (as $0x+0y+z-4=0$).' },
      [
        si('a', 'Vectơ $(0;0;1)$ là một vectơ pháp tuyến của $(\\delta)$.', 'Vector $(0,0,1)$ is a normal vector.', true, 'Hệ số $0,0,1$.', 'Coefficients $0,0,1$.'),
        si('b', 'Mặt phẳng $(\\delta)$ song song với mặt phẳng $Oxy$.', 'Plane $(\\delta)$ is parallel to the $Oxy$ plane.', true, 'Vectơ pháp tuyến cùng phương với $Oz$.', 'Normal parallel to $Oz$.'),
        si('c', 'Gốc tọa độ $O$ thuộc $(\\delta)$.', 'The origin lies on $(\\delta)$.', false, '$z=0\\neq4$.', '$z=0\\neq4$.'),
        si('d', 'Điểm $B(0;0;4)$ thuộc $(\\delta)$.', 'Point $B(0,0,4)$ lies on $(\\delta)$.', true, '$z=4$ thỏa phương trình.', '$z=4$ satisfies the equation.'),
      ],
      { vi: 'Đáp án: aĐ, bĐ, cS, dĐ.', en: 'Answers: aT, bT, cF, dT.' },
      { vi: '**Ý c.** $O$ có $z=0$. **Ý d.** $(0;0;4)$ thuộc mặt phẳng.', en: '**c.** $O$ has $z=0$. **d.** $(0,0,4)$ lies on the plane.' },
      { vi: '$z=4$ là mặt phẳng song song $Oxy$.', en: '$z=4$ is parallel to $Oxy$.' }),

    // P2_04
    tf('P2_04', 8,
      { vi: 'Túi có $3$ bi đỏ và $2$ bi xanh. Rút hai bi không hoàn lại.', en: 'A bag has $3$ red and $2$ blue balls. Two draws without replacement.' },
      [
        si('a', '$P(\\text{bi đỏ đầu}) = \\dfrac{3}{5}$.', '$P(\\text{first red}) = \\dfrac{3}{5}$.', true, '$3$ đỏ trong $5$ bi.', '$3$ red out of $5$.'),
        si('b', '$P(\\text{cả hai đỏ}) = \\dfrac{3}{10}$.', '$P(\\text{both red}) = \\dfrac{3}{10}$.', true, '$\\dfrac{3}{5}\\cdot\\dfrac{2}{4}=\\dfrac{3}{10}$.', '$3/5\\cdot2/4=3/10$.'),
        si('c', 'Hai lần rút độc lập.', 'The two draws are independent.', false, 'Không hoàn lại.', 'Without replacement.'),
        si('d', '$P(\\text{cả hai xanh}) = \\dfrac{1}{10}$.', '$P(\\text{both blue}) = \\dfrac{1}{10}$.', true, '$\\dfrac{2}{5}\\cdot\\dfrac{1}{4}=\\dfrac{1}{10}$.', '$2/5\\cdot1/4=1/10$.'),
      ],
      { vi: 'Đáp án: aĐ, bĐ, cS, dĐ.', en: 'Answers: aT, bT, cF, dT.' },
      { vi: '**Ý b.** $P=\\dfrac{3}{10}$. **Ý d.** $P=\\dfrac{1}{10}$.', en: '**b.** $P=3/10$. **d.** $P=1/10$.' },
      { vi: 'Rút không hoàn lại: cập nhật số bi sau lần đầu.', en: 'Update counts after the first draw.' }),
    tf('P2_04', 9,
      { vi: 'Xét nghiệm: $8\\%$ dân số mắc bệnh; dương tính đúng $90\\%$ khi có bệnh; âm tính đúng $95\\%$ khi không bệnh.', en: 'Test: $8\\%$ disease rate; $90\\%$ true positive; $95\\%$ true negative.' },
      [
        si('a', 'Xác suất không mắc bệnh bằng $0{,}92$.', 'Probability of no disease is $0.92$.', true, '$1-0{,}08=0{,}92$.', '$1-0.08=0.92$.'),
        si('b', 'Xác suất dương tính, biết có bệnh, bằng $0{,}9$.', 'Given disease, $P(\\text{positive})=0.9$.', true, 'Theo dữ kiện.', 'Given in stem.'),
        si('c', 'Xác suất dương tính bằng $0{,}9$.', 'Probability of positive test is $0.9$.', false, '$P(+)=0{,}08\\cdot0{,}9+0{,}92\\cdot0{,}05=0{,}118$.', 'Total probability.'),
        si('d', 'Xác suất không bệnh, biết âm tính, lớn hơn $0{,}99$.', 'Given negative, $P(\\text{healthy})>0.99$.', true, '$\\approx0{,}991$.', '$\\approx0.991>0.99$.'),
      ],
      { vi: 'Đáp án: aĐ, bĐ, cS, dĐ.', en: 'Answers: aT, bT, cF, dT.' },
      { vi: '**Ý c.** $P(+)$ cần công thức xác suất toàn phần.', en: '**c.** Total probability for $P(+)$.' },
      { vi: 'Phân biệt $P(+)$ và $P(+\\mid\\text{bệnh})$.', en: 'Distinguish $P(+)$ and $P(+\\mid\\text{disease})$.' }),

    // P3_01
    short('P3_01', 8,
      { vi: 'Giá trị lớn nhất của $T = 4x + y$ với $x \\ge 0$, $y \\ge 0$, $x + y \\le 8$ bằng', en: 'Max of $T = 4x + y$ with $x \\ge 0$, $y \\ge 0$, $x + y \\le 8$ is' },
      ['32'], 0,
      { vi: 'GTLN tại $(8;0)$: $T=32$.', en: 'Max at $(8,0)$: $T=32$.' },
      { vi: '**Đỉnh:** $(0,0)$, $(8,0)$, $(0,8)$. **$T(8,0)=32$** lớn nhất.', en: '**Vertices.** Max **32** at $(8,0)$.' },
      { vi: 'Hệ số $4$ của $x$ lớn — kiểm tra $(8;0)$.', en: 'Larger $x$ coefficient — check $(8,0)$.' }),
    short('P3_01', 9,
      { vi: 'Giá trị lớn nhất của $T = 2x + 5y$ với $x \\ge 0$, $y \\ge 0$, $x + 3y \\le 15$ bằng', en: 'Max of $T = 2x + 5y$ with $x \\ge 0$, $y \\ge 0$, $x + 3y \\le 15$ is' },
      ['25'], 0,
      { vi: 'GTLN tại $(0;5)$: $T=25$.', en: 'Max at $(0,5)$: $T=25$.' },
      { vi: '**Giao $Oy$:** $(0;5)$. **$T(0,5)=25$.**', en: '**$y$-intercept $(0,5)$.** Max **25**.' },
      { vi: '$x+3y\\le15$ cắt $Oy$ tại $(0;5)$, không phải $(0;15)$.', en: '$y$-intercept is $(0,5)$, not $(0,15)$.' }),

    // P3_02
    short('P3_02', 8,
      { vi: 'Số cách chọn 2 quyển sách từ 10 quyển khác nhau bằng', en: 'Ways to choose 2 books from 10 distinct books' },
      ['45'], 0,
      { vi: '$C_{10}^2 = 45$.', en: '$C_{10}^2 = 45$.' },
      { vi: '**$C_{10}^2 = \\dfrac{10\\cdot9}{2} = 45$.**', en: '**$C_{10}^2 = 45$.**' },
      { vi: 'Chia $2!$ vì không xét thứ tự.', en: 'Divide by $2!$.' }),
    short('P3_02', 9,
      { vi: 'Số cách chọn 4 thành viên từ 8 thành viên bằng', en: 'Ways to choose 4 members from 8' },
      ['70'], 0,
      { vi: '$C_8^4 = 70$.', en: '$C_8^4 = 70$.' },
      { vi: '**$C_8^4 = \\dfrac{8\\cdot7\\cdot6\\cdot5}{4!} = 70$.**', en: '**$C_8^4 = 70$.**' },
      { vi: 'Nhớ chia $4!=24$.', en: 'Divide by $4!=24$.' }),

    // P3_03
    short('P3_03', 8,
      { vi: 'Gieo một xúc xắc. $P(\\text{mặt } \\le 2)$ bằng (phân số tối giản)', en: 'One die. $P(\\text{face } \\le 2)$ (simplest fraction)' },
      ['1/3', '2/6'], 0,
      { vi: 'Hai mặt $\\{1,2\\}$: $P=\\dfrac{2}{6}=\\dfrac{1}{3}$.', en: '$P=2/6=1/3$.' },
      { vi: '**$A=\\{1,2\\}$, $P=\\dfrac{1}{3}$.**', en: '**$P=1/3$.**' },
      { vi: '$\\le 2$ gồm $1$ và $2$, không phải chỉ mặt $2$.', en: 'Two outcomes: $1$ and $2$.' }),
    short('P3_03', 9,
      { vi: 'Gieo hai xúc xắc. $P(\\text{tổng bằng } 10)$ bằng (phân số tối giản)', en: 'Two dice. $P(\\text{sum } 10)$ (simplest fraction)' },
      ['1/12', '3/36'], 0,
      { vi: 'Ba cặp trong $36$ kết quả: $P=\\dfrac{3}{36}=\\dfrac{1}{12}$.', en: 'Three pairs: $P=3/36=1/12$.' },
      { vi: '**Tổng $10$:** $(4,6),(5,5),(6,4)$ — $3$ cặp.', en: '**Three ordered pairs.**' },
      { vi: 'Đếm cặp có thứ tự, $n(\\Omega)=36$.', en: 'Ordered pairs, $36$ outcomes.' }),

    // P3_04
    short('P3_04', 8,
      { vi: 'Nón có $r=5$, $h=6$. Thể tích ($\\pi\\approx3{,}14$, làm tròn số nguyên)', en: 'Cone $r=5$, $h=6$. Volume ($\\pi\\approx3.14$, round to integer)' },
      ['157'], 1,
      { vi: '$V=\\dfrac{1}{3}\\cdot3{,}14\\cdot25\\cdot6\\approx157{,}08\\rightarrow157$.', en: '$V\\approx157$.' },
      { vi: '**$V=\\dfrac{1}{3}\\pi r^2 h\\approx157$.**', en: '**$V\\approx157$.**' },
      { vi: 'Hệ số $\\dfrac{1}{3}$ cho nón.', en: 'Factor $\\dfrac{1}{3}$ for cone.' }),
    short('P3_04', 9,
      { vi: 'Nón có $r=3$, $h=10$. Thể tích ($\\pi\\approx3{,}14$, làm tròn số nguyên)', en: 'Cone $r=3$, $h=10$. Volume ($\\pi\\approx3.14$, round)' },
      ['94'], 1,
      { vi: '$V=\\dfrac{1}{3}\\cdot3{,}14\\cdot9\\cdot10\\approx94{,}2\\rightarrow94$.', en: '$V\\approx94$.' },
      { vi: '**$r^2=9$, $V\\approx94$.**', en: '**$V\\approx94$.**' },
      { vi: '$r^2=9$, không phải $3$.', en: '$r^2=9$.' }),

    // P3_05
    short('P3_05', 8,
      { vi: 'GTNN của $f(x)=x^2-8x+10$ trên $\\mathbb{R}$ bằng', en: 'Minimum of $f(x)=x^2-8x+10$ on $\\mathbb{R}$' },
      ['-6'], 0,
      { vi: '$x=4$, $f(4)=-6$.', en: '$f(4)=-6$.' },
      { vi: '**$f\'(x)=2x-8=0 \\Rightarrow x=4$, $f(4)=-6$.**', en: '**$f(4)=-6$.**' },
      { vi: 'Thế $x=4$ vào $f(x)$.', en: 'Evaluate $f(4)$.' }),
    short('P3_05', 9,
      { vi: 'GTNN của $f(x)=2x^2-4x+1$ trên $\\mathbb{R}$ bằng', en: 'Minimum of $f(x)=2x^2-4x+1$ on $\\mathbb{R}$' },
      ['-1'], 0,
      { vi: '$x=1$, $f(1)=-1$.', en: '$f(1)=-1$.' },
      { vi: '**$x=1$, $f(1)=2-4+1=-1$.**', en: '**$f(1)=-1$.**' },
      { vi: 'GTNN có thể âm.', en: 'Minimum can be negative.' }),

    // P3_06
    short('P3_06', 8,
      { vi: '$\\displaystyle \\int_0^1 3x^2\\,dx$ bằng', en: '$\\displaystyle \\int_0^1 3x^2\\,dx$ equals' },
      ['1'], 0,
      { vi: '$[x^3]_0^1=1$.', en: '$[x^3]_0^1=1$.' },
      { vi: '**Nguyên hàm $x^3$, $F(1)-F(0)=1$.**', en: '**Answer 1.**' },
      { vi: 'Thế cả cận dưới.', en: 'Evaluate both bounds.' }),
    short('P3_06', 9,
      { vi: '$\\displaystyle \\int_1^2 \\dfrac{1}{x}\\,dx$ bằng ($\\ln 2$, làm tròn hai chữ số thập phân)', en: '$\\displaystyle \\int_1^2 \\dfrac{1}{x}\\,dx$ equals ($\\ln 2$, round to 2 decimals)' },
      ['0.69', '0,69'], 0.01,
      { vi: '$[\\ln x]_1^2=\\ln2\\approx0{,}69$.', en: '$[\\ln x]_1^2=\\ln2\\approx0.69$.' },
      { vi: '**$\\ln2\\approx0{,}69$.**', en: '**$\\ln2\\approx0.69$.**' },
      { vi: 'Tích phân $\\int 1/x\\,dx = \\ln|x|+C$.', en: 'Antiderivative is $\\ln|x|$.' }),
  ];
}

export const BATCH4_NOTES = {
  'bank-p1-01-b08': 'sin 60° = √3/2',
  'bank-p1-01-b09': 'cos 45° = √2/2',
  'bank-p1-02-b08': 'CSC u1=3, d=2, u5=11',
  'bank-p1-02-b09': 'CSN u1=2, q=3, u5=162',
  'bank-p1-03-b08': 'Lăng trụ vuông cạnh 5, h=4, V=100',
  'bank-p1-03-b09': 'Chóp tam giác vuông AB=3, AC=4, SA=5, V=10',
  'bank-p1-04-b08': 'Hình cầu R=5, V=500π/3',
  'bank-p1-04-b09': 'Hình cầu R=1, S=4π',
  'bank-p1-05-b08': '2^x=32, x=5',
  'bank-p1-05-b09': 'log₂ x=4, x=16',
  'bank-p1-06-b08': 'Trung bình 2,4,6,8 = 5',
  'bank-p1-06-b09': 'Trung vị n=18, nhóm [10;15)',
  'bank-p1-07-b08': 'Đạo hàm x²+5x = 2x+5',
  'bank-p1-07-b09': 'f(x)=x²-4x+1, f\'(2)=0',
  'bank-p1-08-b08': 'Nguyên hàm x³ = x⁴/4 + C',
  'bank-p1-08-b09': '∫₀²(3x+1)dx = 8',
  'bank-p1-09-b08': 'Nguyên hàm cos x = sin x + C',
  'bank-p1-09-b09': '∫₀^π sin x dx = 2',
  'bank-p1-10-b08': 'Khoảng cách M(1;2;2) đến O = 3',
  'bank-p1-10-b09': 'Khoảng cách N(3;0;4) đến O = 5',
  'bank-p1-11-b08': 'Đường thẳng, vectơ chỉ phương (3;2;1)',
  'bank-p1-11-b09': 'Đường thẳng, vectơ chỉ phương (2;-1;1)',
  'bank-p1-12-b08': 'Mặt phẳng 3x-y+z-5=0, n=(3;-1;1)',
  'bank-p1-12-b09': 'Mặt phẳng -x+2y+z+4=0, n=(-1;2;1)',
  'bank-p2-01-b08': 'f(x)=2x³-6x, cực trị và đồng biến',
  'bank-p2-01-b09': 'f(x)=-x²+6x-5, GTLN=4 tại x=3',
  'bank-p2-02-b08': '∫₀¹(x+2)dx = 2,5',
  'bank-p2-02-b09': '∫₁⁴ x dx = 15/2, TB = 5/2',
  'bank-p2-03-b08': 'Mặt phẳng x+y+z-2=0, O không thuộc',
  'bank-p2-03-b09': 'Mặt phẳng z=4 song song Oxy',
  'bank-p2-04-b08': '3 đỏ 2 xanh, P(cả hai đỏ)=3/10',
  'bank-p2-04-b09': 'Sàng lọc 8% bệnh, Bayes',
  'bank-p3-01-b08': 'QHTT max T=4x+y, GTLN=32',
  'bank-p3-01-b09': 'QHTT max T=2x+5y, GTLN=25',
  'bank-p3-02-b08': 'C₁₀² = 45',
  'bank-p3-02-b09': 'C₈⁴ = 70',
  'bank-p3-03-b08': 'Xúc xắc, P(mặt ≤2)=1/3',
  'bank-p3-03-b09': 'Hai xúc xắc, P(tổng=10)=1/12',
  'bank-p3-04-b08': 'Nón r=5, h=6, V≈157',
  'bank-p3-04-b09': 'Nón r=3, h=10, V≈94',
  'bank-p3-05-b08': 'GTNN x²-8x+10, f(4)=-6',
  'bank-p3-05-b09': 'GTNN 2x²-4x+1, f(1)=-1',
  'bank-p3-06-b08': '∫₀¹ 3x² dx = 1',
  'bank-p3-06-b09': '∫₁² 1/x dx ≈ 0,69',
};
